---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio1
  labels: 
    name: portfolio1
    app: website
spec: 
  replicas: 3
  selector:
    matchLabels:
      name: portfolio1-pod
      app: website
  template:
    metadata:
      name: portfolio1-pod
      labels: 
        name: portfolio1-pod
        app: website
    spec:
      containers:
        - name: portfolio1
          image: roland007/rolanduk
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: portfolio1
  labels:
    name: portfolio1-service
    app: website
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: portfolio1-pod
    app: website
---
