---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
  namespace: sock-shop

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: front-end
